services:
  stoodo-api:
    restart: always
    image: 'stoodo-api'
    build: .
    depends_on:
      stoodo-database:
        condition: service_healthy
    ports:
      - '8080:8080'
  stoodo-gui:
    restart: always
    image: 'stoodo-gui'
    build: frontend/stoodo/
    ports:
      - '3001:3001'
  stoodo-database:
    image: 'postgres:15.2'
    restart: always
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'" ]
      interval: 10s
      timeout: 3s
      retries: 3
